version: "3.9"

services:
  mongodb:
    image: mongo:4.4.5
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-pass}
    ports:
      - "0.0.0.0:${MONGO_PORT:-27017}:27017"
    restart: always

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS:-pass}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_DB:-threatmapper}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST:-mongodb}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:-27017}
    ports:
      - "0.0.0.0:${MONGO_EXPRESS_PORT:-8081}:8081"
    depends_on:
      - mongodb


  scraper:
    build: ./scraper
    command: poetry run python ./src/main.py
    environment:
      MONGO_USER: ${MONGO_USER:-root}
      MONGO_PASS: ${MONGO_PASS:-pass}
      MONGO_HOST: ${MONGO_HOST:-mongodb}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_DB: ${MONGO_DB:-scraper}
      MONGO_REVIEWS_COLL: ${MONGO_COLL:-reviews}
      MONGO_RECIPES_COLL: ${MONGO_COLL:-recipes}
      MONGO_PROFILES_COLL: ${MONGO_COLL:-profiles}
      SELENIUM: ${SELENIUM:-selenium}
    depends_on:
      #      - mongodb
      - selenium
    restart: always


  selenium:
    image: selenium/standalone-firefox:88.0
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: '2gb'
    logging:
      driver: none

